### ISSUE TITLE
Add more available ports

### ISSUE THREAD

**Issue by RapsIn4** [m26jiang/LeHearts_Server#4]

**Comment by Hextortion** [comment]
Cheng, we need you to make the server accept connections on more than one port. This way, we should be able to make multiple connections to server on the same machine.

This will allow us to test the functionality of the server.

**Comment by m26jiang** [comment]
^

**Comment by aurtistictrader** [comment]
Sure. Trivial fix, but when I tried it earlier it can accept multiple connections after game started

I am a faggot.

**Comment by Hextortion** [comment]
So what exactly did you try? You connect to the server using multiple clients on the same port? Please be more specific.

**Comment by Hextortion** [comment]
Closed because this is no longer necessary.
